## Tensorflow 基本語法 ([網站](https://ithelp.ithome.com.tw/users/20119971/ironman/2254))

### 數據類型

​tensor在數學裡主要講的就是 “向量”，簡單來說就是一個n維度的data。 <br>
主要支援資料格式就是一般的data type。包含: int , float , double , string , bool <br>

所以我們要建立一個tf.tensor可以直接如下來建立tensor

In [8]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.9.1'

In [4]:
tf.constant(6)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [5]:
tf.constant(6.)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [6]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant("I love TF2")

<tf.Tensor: shape=(), dtype=string, numpy=b'I love TF2'>

### 變數類型
TF變數類型主要有三種，tf.constant、tf.Variable 以及 tf.placeholder。


**tf.constant:** <br>
顧名思義，他就是一個constant的類別，你可以放入各式的資料型態，做一些基礎運算，Ex: tf.add 等等。 <br>
使用時機像是有時候我們會放accuracy或者一些運算完的模型資訊等等。因此，在創建一些tf.constant的可以簡單的用上面語法或者是你假如有一個numpy array也可以直接使用 tf.convert_to_tensor

In [9]:
# Create tf.constant
a = tf.constant([1,2,3])
# Convert np arry to tf
a= np.array([1,2,3])
b = tf.convert_to_tensor(a)

**tf.Variable** <br>
簡單來說，tf.variable就是放置可學習的變數或者說將可求導的變數，例如: Neural Network的wieght或者bias。因此，在tf.variable中會紀錄他是learnable 或者在autograph中可被求導變數。之後，會實作簡單的一個NN會更清楚他的用途。

In [11]:
# Create tf.Variable
a = tf.ones(6)
b = tf.Variable(a, name = 'Data_point')

b

<tf.Variable 'Data_point:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [12]:
b.dtype #check data tpye

tf.float32

In [13]:
b.name #check name

'Data_point:0'

In [14]:
b.trainable #check weather trainable

True

**tf.placeholder** <br>
主要是TF在計算Gaph的方法。在使用時，我們是不會先給定一個初始值，而是給定長度或者資料格式先佔有一個空間。簡單來說就是，和Variable或者constant不一樣的是，不需給定初始值，但必須預先定義好資料類型與長寬深度。主要使用為在train模型，我們會放 x 與 y 的資料。在看TF1.X的程式會很常看到這個變數。在TF2.0中，已經不使用這個變數，蠻多都改成使用tf.data的api在導資料。而且在TF2.0中，在eager execution下，也不需要去預先定義這些資料空間。

### 簡單建立資料
有時候我們會想簡單建立有些都是0的資料，所以我們可以用一些簡單的TF語法來建立

In [15]:
#Example create zero
a = tf.zeros([6,6])
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [16]:
#or
b = tf.zeros_like(a)
b

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
#or fill -> shape and fill nums
c = tf.fill([6,6],0)
c

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])>

建立一個random matrix，此時我們可以使用下面各式不同的distribution來建立。 <br>
這樣的random方法我們常用於initial Deep learning中的weight或bias。 <br>
因為，當你的weight不是random產生，而是一個齊一性的matrix，會讓您所學出來的權重都是一樣，網路會變成純粹的線性。 <br>

**權重均必須random產生**

In [18]:
#Example random by normal distribution
a = tf.random.normal([6,6],mean=0,stddev=1)
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[ 1.5988526 ,  0.1406798 , -0.30346355, -0.7026813 ,  0.5813478 ,
         0.9994943 ],
       [-0.45355526, -1.3237975 , -0.6967904 ,  0.78399515, -0.5458028 ,
        -0.10231382],
       [-0.7176008 , -1.2546759 ,  0.8180643 , -1.017536  ,  1.3700936 ,
         0.8958166 ],
       [-0.25636756, -0.9434931 , -0.07298949, -1.5354348 ,  2.062475  ,
        -1.0037172 ],
       [ 2.068513  , -0.2696432 , -0.6414222 , -1.4308274 , -1.1564838 ,
        -0.45188615],
       [ 0.21189198,  0.33802333, -1.1058456 ,  2.436304  , -2.223485  ,
         0.5848353 ]], dtype=float32)>

In [19]:
#random by truncated normal distribution
b = tf.random.truncated_normal([6,6],mean=0,stddev=1)
b

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[ 0.8571428 ,  1.3245986 ,  1.3602015 ,  1.7722728 ,  1.0745045 ,
         0.16345483],
       [ 0.24180356,  0.9247242 , -0.2823902 ,  1.1697292 ,  0.28993955,
        -0.39261475],
       [-0.77013093,  1.7253994 , -0.69616145, -0.8288765 , -0.33480766,
        -0.41696244],
       [-0.34874108, -0.36068428, -0.2794822 , -0.24372216, -0.61089283,
         0.10393757],
       [-1.4721991 , -0.778645  , -1.5918306 ,  1.3904209 , -0.16383505,
        -1.3493391 ],
       [-0.7558181 , -0.18061377, -1.4750434 ,  1.6862315 , -0.5099955 ,
        -1.5525311 ]], dtype=float32)>

In [20]:
#random by uniform
c = tf.random.uniform([6,6],minval=0,maxval=1)
c

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0.5571766 , 0.1095351 , 0.44586718, 0.7577535 , 0.42640913,
        0.34921026],
       [0.66029406, 0.44906235, 0.03302848, 0.40366983, 0.8328757 ,
        0.04164398],
       [0.26406515, 0.47387958, 0.03155053, 0.9853147 , 0.74855995,
        0.96852183],
       [0.7245778 , 0.0039351 , 0.21977198, 0.77969384, 0.21166825,
        0.79275334],
       [0.58730114, 0.26699448, 0.16617465, 0.131966  , 0.02241194,
        0.9668703 ],
       [0.7247833 , 0.3506304 , 0.13597906, 0.59281933, 0.5439019 ,
        0.4334725 ]], dtype=float32)>

### 選取資料
有時候，我們可能想將資料選取資料，看一下資料長什麼樣子。尤其是當我們想選出特定的row或者index該如何做呢？可以利用下面的語法

In [ ]:
#Example for select instance
a = tf.ones([1,5,5,3])
a[0][0].shape   #Output shape:TensorShape([5, 3])
a

In [ ]:
a[...,2].shape  #Output shape:TensorShape([1, 5, 5])
a

### Reshape

一般來說，以一個影像辨識的data shape，我們會將資料擺成 [batch, height(row), width(columns),channel] 。Ex: [128,64,64,1]。因次第一個說明的就是最常看到的reshape

***


想資料轉換樣式，或者是把shape轉成我們想要的樣式 <br>
Ex: [64,32,32] -> [64, 32*32]，將想是將一個image[b,h,w,3] 轉成 [b,pixcel,3]。類似將一個2維度的Matrix轉成一個1維度的array。

In [29]:
#Create samples
a = tf.random.normal([6,32,32,3])

#Reshape to different type
tf.reshape(a,[6,32*32,3]).shape 

TensorShape([6, 1024, 3])

In [30]:
# 將reshape中的欄位設為-1，他會自動計算
tf.reshape(a,[6,-1,3]).shape    

TensorShape([6, 1024, 3])

一次使用兩次reshape來轉換資料

In [27]:
tf.reshape(tf.reshape(a,[6,-1]),[6,16,-1,3]).shape
#Output:TensorShape([6, 16, 64, 3])

TensorShape([6, 16, 64, 3])

### Transpose

當你想要將matrix的欄位對調，Ex; [6,32,32,3] -> [6,32,3,32]，就可以使用transpose來對調。 <br>
有時候會將[b,h,w,3] -> [b,3,h,w] (Pytorch格式)，就可以使用tf.transpose來轉。

In [31]:
tf.transpose(a,perm=[0,1,3,2]).shape

TensorShape([6, 32, 3, 32])

### Expand_dims
當如果您想到增加一個維度，例如原本你有一個 [32,32,3]的圖，但您想新增新的一維度來記錄他的資料量，或者一個batch的量。就可以使用tf.expamd_dims來新增。

In [32]:
a = tf.random.normal([32,32,3])
tf.expand_dims(a,axis=0).shape

TensorShape([1, 32, 32, 3])

### Broadcasting
Broadcast的function就是broadcast數值，但實際上，儲存或者variable size都是沒有變化，不會去複製data。 <br> 
因此，有較好的儲存效率。簡單的案例就像是我們在做Linear regression的時候，在 X*W+b的時候，通常b會以broadcast的方式來執行 (之後會有實作Linear regression)。

* 概念: 當a 和 b 維度不一致時 (a=[4,32,32,3], b=[3])，做broadcast的時候，會先向右靠齊然後增加維度相加 (b會broadcast -> [3] -> [1,1,1,3] -> [4,32,32,3] 和a做運算)，也就是說他會exapand成相同的size。

* 應用情境：今天公司有4個部們，40個員工，以及他們每個月的薪資，因為今天公司發大財，想要幫所有員工加薪，因此我們可能會組成一個matrix A = [4,40,12]，現在我們有另外一個每個月調薪的matrix B = [40,1]。這時候就可以用broadcast將所有人一次加薪，假如今天公司想要針對每個月加不一致的薪水，matrix B = [12]。

(註: broadcast的時候，要對齊最右邊的那個維度，若非1，則必須相等)

In [33]:
x = tf.random.normal([4,40,12])
(x + tf.random.normal([40,1])).shape

TensorShape([4, 40, 12])

註1: 因為broadcast是一種內建的優化方式，TF會自斷判斷是否可以broadcast，不用特別寫broadcast <br>
註2:假如你想broadcast且b的維度變成broadcast 後的相同維度，可以參考tf.broadcast_to 以及tf.tile

### Merge and Split
假如我今天有兩個資料，想要以row wise的方式合併在一起，Ex: (#row,#cols) A[6,12] + B[6,12] = [12,12]。此時，可以使用tf.concat來合併資料。

In [34]:
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.concat([a,b],axis=0).shape

TensorShape([12, 32, 3])

此外，可以透過axis來調控你要合併by哪一個axis

In [35]:
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.concat([a,b],axis=1).shape

TensorShape([6, 64, 3])

假如我今天有兩個資料，想要以column wise的方式合併在一起，類似新增一個column，Ex: (#row,#cols) A[6,12] + B[6,12] = [2,6,12]。此時，可以使用tf.stack來合併資料。

In [36]:
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.stack([a,b],axis=0).shape

TensorShape([2, 6, 32, 3])

Split的話，這邊會比較unstack跟split的用法
unstack與stack正好相反，也就是拿掉Column

In [37]:
a = tf.ones([2,32,3])
aa,ab= tf.unstack(a,axis=0)
aa.shape
#Output:TensorShape([32, 3])
data_all = tf.unstack(a,axis=1)
data_all[0].shape
#Output:TensorShape([2, 3])
len(data_all)

32

split的話就會比較直觀，就是直接針對指定Column然後切幾分這樣。

In [38]:
data_all = tf.split(a,axis=1,num_or_size_splits=2)
data_all[0].shape
#Output:TensorShape([2, 16, 3])
len(data_all)

2

### Sort
從字面來看就是排序，有時候需要透過sort來排序feature並針對排序後的資料來畫圖或者來檢驗您對資料的假設。 <br>
又或者我今天講把預測不好的後100筆資料拿出來驗證模型模型問題。都可以使用這樣的方法。這邊會介紹兩種方法，一種是純粹的sort，一種是sort後output是index，你就可以拿index來針對特定feature畫圖。

In [39]:
#Example for sort
data = tf.random.normal([10],mean=0,stddev=1)
tf.sort(data,direction='DESCENDING')

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.3792018 ,  0.7950544 ,  0.52371716,  0.3672976 ,  0.20072214,
        0.15889104, -0.01921773, -0.5998441 , -1.1084162 , -1.945121  ],
      dtype=float32)>

In [40]:
#or
tf.gather(data,tf.argsort(data,direction='ASCENDING'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.945121  , -1.1084162 , -0.5998441 , -0.01921773,  0.15889104,
        0.20072214,  0.3672976 ,  0.52371716,  0.7950544 ,  1.3792018 ],
      dtype=float32)>

拿top k 個就可以使用tf.math.top_k，他會同時return numer以及index

In [43]:
#Example top_k
top_data = tf.math.top_k(data,5)
top_data

TopKV2(values=<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.3792018 , 0.7950544 , 0.52371716, 0.3672976 , 0.20072214],
      dtype=float32)>, indices=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 9, 6, 1, 4])>)

In [46]:
top_data.values

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.3792018 , 0.7950544 , 0.52371716, 0.3672976 , 0.20072214],
      dtype=float32)>

### Padding
在做影像辨識的時候，有時候我們會做padding，而padding的作用是什麼呢？1. 針對差異圖片的大小做補齊，有時候可能輸入和filter不一致時，可以透過padding補齊。2. 有時候我們希望增加邊界訊息量，一般來說，沒做padding邊界只會被掃到一次，若做padding可以增加被掃到的次數，這邊簡單的說明padding及example，之後講CNN的時候會更詳細說明。

In [47]:
data = tf.random.normal([3,3],mean=0,stddev=1)
tf.pad(data,[[1,1],[1,1]])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9941075 , -0.3805162 , -1.0929228 ,  0.        ],
       [ 0.        , -0.32113233,  0.38333318, -0.13180594,  0.        ],
       [ 0.        ,  0.06274855, -0.720729  ,  0.5564854 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)>

### Clipping
做Deep learning計算gradient的時候，有時候會遇到gradient exploding。我們可預期當一個數字累乘 (1.01**100)，你的gradient會變超大。所以，解決的方法簡單來說就是超過一個門檻值就固定，或者重新使用tf.clip_by_norm，這個方法就比較進階一點，他是針對整個data做縮放

In [48]:
#Example clipping
tf.clip_by_value(data,0,1)
#range if number less or above fix at 0 or 1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9941075 , 0.        , 0.        ],
       [0.        , 0.38333318, 0.        ],
       [0.06274855, 0.        , 0.5564854 ]], dtype=float32)>

### 基本數學運算
首先我們先從基本數學運算開始談起，這些運算您將會大量使用於DL or ML專案。雖然TF有很多已經寫好的實用function，但有時候可能還是無法達到一些客製化(老闆)需求，所以您可能還是需要自己寫function來運算一些指標或者修改loss function等等。接下來會討論一下基本運算。[ + - X % sqrt ...等等]，此外，運算時也要注意用法。

*Element wise: 直接對相對應的元素相加，Ex: +- <br>
*Matrix wise: 矩陣相乘，Ex: [6,32,4] @ [6,4,6] = [6,32,6] <br>
*Dimention wise: 針對特定dimention做運算。Ex: 對整個dimention做reduce_mean。 <br>

In [49]:
#Example for element wise
a = tf.fill([2,2],5)
b = tf.fill([2,2],6)
a+b,a*b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 11],
        [11, 11]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]])>)

In [50]:
#Example for Matrix wise
a = tf.fill([2,32,4],5)
b = tf.fill([2,4,6],6)
(a@b).shape 

TensorShape([2, 32, 6])

以Dimension wise的來做sample，為來在算一些loss，或者計算accuracy會常用

In [51]:
#Example for dimension wise
data = [[1,2,3],
      [1,2,3]]

tf_data = tf.cast(x,tf.float32)

mean_all = tf.reduce_mean(tf_data, keepdims=False)
mean_0 = tf.reduce_mean(tf_data, axis=0, keepdims=False)
mean_1 = tf.reduce_mean(tf_data, axis=1, keepdims=False)

mean_all,mean_0,mean_1

(<tf.Tensor: shape=(), dtype=float32, numpy=0.071469165>,
 <tf.Tensor: shape=(40, 12), dtype=float32, numpy=
 array([[ 4.62767512e-01,  4.22995597e-01, -3.79276574e-01,
          1.45967364e+00, -9.10601243e-02, -3.34578961e-01,
         -1.12569138e-01, -4.54907179e-01,  1.32996514e-01,
         -5.20453453e-01, -4.99596119e-01, -5.90019822e-01],
        [ 1.54554874e-01, -6.11201078e-02,  7.81866789e-01,
         -5.94453990e-01, -2.81887650e-02, -2.42647588e-01,
         -3.03398520e-01,  2.88090497e-01, -2.57269472e-01,
         -4.44746941e-01, -5.53212967e-03,  1.66807562e-01],
        [ 2.38552570e-01,  1.12571454e+00, -6.60131335e-01,
          1.87938988e-01,  9.82534438e-02,  6.84534490e-01,
          4.70536441e-01,  4.72973406e-01,  1.89928591e-01,
          6.38936937e-01, -9.84002650e-01, -9.90714550e-01],
        [-3.52567345e-01,  7.71643519e-01,  1.71860963e-01,
         -5.50930440e-01,  5.28669298e-01,  9.14733827e-01,
         -4.33631063e-01,  1.35800242e-01,  7.95

可以清楚的看到他會去計算by你所設定的axis，針對特定axis計算mean。